### ISSUE TITLE
Glossarist Ruby "concept" gem (move IEV specific parsing back to iev-data)

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#1]
From metanorma/stepmod-utils#14:

We need a Ruby gem to deal with the https://github.com/glossarist/concept-model model.

This will allow us to use the same basis for ingesting concepts as well exporting them.

This gem will be used in metanorma/metanorma-standoc#255 by @opoudjis .

**Comment by skalee** [comment]
@opoudjis Can you confirm that I can support Ruby 2.4.4+ only, i.e. without Ruby 2.4.0-2.4.3, particularly in context of packed-mn requirements?

This is a bit broader question in fact. I'm not sure yet if I'll use Zeitwerk in this very project, but certainly I'll be tempted to do so in some other gems I develop, some of them useful or potentially useful in Metanorma. For instance, ReverseAdoc could benefit greatly from Zeitwerk, given current `require` hell (of course I won't do that without prior discussion):

https://github.com/metanorma/reverse_adoc/blob/aec203d80eafd6cb23828013f102f3a8b0dafba3/lib/reverse_adoc/html_converter.rb#L3-L35

**Comment by ronaldtse** [comment]
Concerns about packed-mn will be answered by @CAMOBAP and @alexeymorozov. 

Simplifying requires are good but want to make sure the solution will be clean.

**Comment by alexeymorozov** [comment]
@skalee We're currently doing and an upgrade from Ruby 2.4.2 (which is already supported) to higher versions (2.4.3 and 2.50 specifically). In my opinion it would be done in the next several days. Even if it wouldn't, we can upgrade it to 2.4.4.

**Comment by ronaldtse** [comment]
Ping @skalee when do you think we can get this ready? It's becoming a blocker for a number of tasks. Thanks!

**Comment by alexeymorozov** [comment]
@skalee I'm merging the 2.4.3 now, and starting 2.4.4 instead of 2.4.10/2.5.

**Comment by skalee** [comment]
@ronaldtse I've overlooked this notification, sorry for late answer! I'll post a more detailed response tomorrow.

> I'm merging the 2.4.3 now, and starting 2.4.4 instead of 2.4.10/2.5.

Thanks for info!

**Comment by skalee** [comment]
I guess tomorrow I'll release first version, but it will be far from complete (no validations, some minor legacy gotchas).  Complete enough for IEV XLS parser, though. I was going to make it nice from the beginning, but I've spent much time on that and I guess I'll rather start with something very simplistic, and then add improvements gradually.

**Comment by ronaldtse** [comment]
@skalee is the gem ready?
