### ISSUE TITLE
Support "parts of speech"

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#2]
See https://github.com/metanorma/metanorma-standoc/issues/249

**Comment by skalee** [comment]
Basically designations are now hashes and accept everything, including "part of speech". I'm going to replace them with dedicated classes, and they'll have "parts_of_speech" attribute, as well as the other grammar ones.

**Comment by ronaldtse** [comment]
Ping @skalee we need to move ahead here...

**Comment by ronaldtse** [comment]
Thanks, closing this.
