### ISSUE TITLE
Add individual "Designation" class

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#24]
We need to represent individual "Designation" s, as they may have usage info that differs from other designations.

**Comment by HassanAkbar** [comment]
@ronaldtse There is a separate model for designations in the Glossarist gem added in [Introduce Designation models](https://github.com/glossarist/glossarist-ruby/pull/21) PR. Can we close this issue or is there anything else we need to do in the scope of this issue?

**Comment by ronaldtse** [comment]
Yes it is sufficient. Thanks! Closing.
