### ISSUE TITLE
Enum strictness

### ISSUE THREAD

**Issue by skalee** [glossarist/glossarist-ruby#4]
https://github.com/glossarist/concept-model defines many enums. For example, designation's normative status can be either `preferred`, `admitted`, or `deprecated`.

> ![Zrzut ekranu 2021-05-07 o 20 37 09](https://user-images.githubusercontent.com/154287/117494055-177bf980-af74-11eb-9a8a-115172e51f91.png)

Is it possible that some glossaries will require custom values for these enums? For example, normative status in glossary X limited to `preferred` and `deprecated`, whereas normative status in glossary Y extended to e.g. `preferred`, `admitted`, `discouraged` (instead of deprecated), `obsoleted`, `under_review`?

I'm asking because I'm going to validate data, and I wonder if allowed values can be hardcoded in `glossarist` gem, or maybe they should be configurable per glossary? This may have some impact on technology stack.

cc @ronaldtse @opoudjis

**Comment by ronaldtse** [comment]
@skalee initially we will be using an identical schema for administrative data (incl. NormativeStatus) because the users are ISO and IEC. Other organizations may be supported in the future that utilize different statuses.

**Comment by ronaldtse** [comment]
To add to this, yes the list of accepted statuses can differ per glossary. If they can be read through a config that would be great.
