### ISSUE TITLE
add a `ConceptSet` class in glossarist

### ISSUE THREAD

**Issue by HassanAkbar** [glossarist/glossarist-ruby#49]
we should have a class called ConceptSet. This Set will have the bibliographic data

**Comment by ronaldtse** [comment]
Originally from https://github.com/geolexica/isotc204.geolexica.org/pull/12#discussion_r973148842

The "ConceptSet" instance represents a set of Glossarist concepts, which also includes:
* a set of bibliographic items that link with those concepts (e.g. if they are sourced, or they include cross-references to bibliographic items in definitions)
* figures, images and assets (e.g. videos) used by those concepts (e.g. used in definitions, notes and examples)

All these objects need to have their own Ruby class definitions.

**Comment by HassanAkbar** [comment]
@ronaldtse For clarification what we should do is create a new class named `ConceptSet` and that class will have further 2 attributes `ManagedConceptCollection` and `Bibliography`. something like below.

```ruby
class ConceptSet
  attr_accessor :concept_collection, :bibliography
end
```

Is this what you have in mind or am I going in the wrong direction?

**Comment by ronaldtse** [comment]
@HassanAkbar yes this is correct. Something like this:

```ruby
class ConceptSet
  attr_accessor :concepts, # concepts leads to a collection of `Concept`s
                :bib_db # bib_db leads to a `BibliographicItems` object

  # The `concept` objects in `concepts` can refer to Relaton references in the `bib_db`
  def initialize(concepts)
    # ...
    # Fills in the bib_db
    concepts.each do |concept|
      bib_db.add(concept.ref) if concept.ref
    end
  end
end

# Relaton provides some basic classes to work with bibliographic items
class BibliographicItems < Relaton::Database
   # ...
end
```

**Comment by HassanAkbar** [comment]
@ronaldtse What I have done so far

- Created class `Glossarist::ConceptSet` which contains
  - concepts -> `Glossarist::ManagedConceptCollection` object
  - bibliographies -> `BibliographyCollection` object
  - assets -> `Collections::AssetCollection` object
  - references -> `Collections::ReferenceCollection` object
- Created class `BibliographyCollection` which inherits from `Relaton::Db` and implement methods to fetch the sources of all concpets.
- Created class ``Collections::ReferenceCollection` which keeps track of all the references and their related concepts.

**Questions**

- For `Collections::AssetCollection` How are we going to initially populate this? Will the list of assets be passed to it or will it be genertaed by us using some algorithm that will work based on the concepts collection?

**Comment by ronaldtse** [comment]
> For Collections::AssetCollection How are we going to initially populate this? Will the list of assets be passed to it or will it be genertaed by us using some algorithm that will work based on the concepts collection?

Yes, assets are passed to it on the creation of the ConceptSet.
