### ISSUE TITLE
Add support for reading authoritativeSource

### ISSUE THREAD

**Issue by HassanAkbar** [glossarist/glossarist-ruby#74]
Need to add support to read `authoritativeSource` (in camel case) as mentioned here -> https://github.com/geolexica/jekyll-geolexica/issues/12

**Comment by ronaldtse** [comment]
Am I missing some context here? Why do we want to use "authoritativeSource" instead of the "sources -> type: authoritative" now?

**Comment by HassanAkbar** [comment]
@ronaldtse This ticket was created to handle `authoritativeSource` key present in [metaverse-glossary](https://github.com/MetaverseStandards/metaversestandards-glossary/tree/main/msfglossary/localized-concept), but that was handled in `Jekyll-geolexica`.

So should I close this ticket?

**Comment by ronaldtse** [comment]
Yes, thanks!
