### ISSUE TITLE
Update to glossarist model v2

### ISSUE THREAD

**Issue by HassanAkbar** [glossarist/glossarist-ruby#76]
Update glossarist to support model v2 as discussed here -> https://github.com/geolexica/jekyll-geolexica/issues/12#issuecomment-1662015937

**Comment by HassanAkbar** [comment]
@ronaldtse @strogonoff @ribose-jeffreylau Do we have the Glassarist Model V2 documented anywhere ? I will be needing that.

**Comment by ronaldtse** [comment]
@HassanAkbar I don't think so. Can you please help update the https://github.com/glossarist/concept-model/ repository for the modeling, and also document the Glossarist YAML format using YAML schema?
