### ISSUE TITLE
Operations on the Concept class: How to add a note? How to add a designation?

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#82]
Operations on the Concept class: How to add a note? How to add a designation?

Need corresponding methods.

**Comment by HassanAkbar** [comment]
@ronaldtse Currently there are 2 options to add notes to a concept class
1. We can do `concept.notes = ["content for note 1", "content for note 2", ...]`, this will make the required concept objects with content set to the string in the array.
2. We can pass a hash i.e `concept.notes = [{content: "content for note 1"}, {content: "content for note 2", sources: [...]}, ...]` with this method we can also pass `source` for the concept.

I'm working on adding complete documentations for what is currently implemented in Glossarist and I'll open a PR for that once done.

**Comment by ronaldtse** [comment]
I want to make it possible to add notes one by one, not using `=`.

e.g.
```
concepts.notes << "content for note"
concepts.notes << {content: "content for note"}
```

**Comment by ronaldtse** [comment]
Also for `designation`. Thanks.

**Comment by HassanAkbar** [comment]
@ronaldtse Currently there is no way to add a single `note` or `designation`. I am adding that & will open a PR for that today.
