### ISSUE TITLE
Add documentation on how to create a Glossarist dataset

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#83]
What are the key files of a Glossarist dataset? The description YAML, concept YAML files... etc.

**Comment by HassanAkbar** [comment]
@ronaldtse we need 2 folders for creating a concept dataset (both folder names are singular)
1. concept
2. localized_concept

Currently there is no documentation for `Glossarist Model V2` so I've followed what was done in [`isotc211-glosary`](https://github.com/geolexica/isotc211-glossary/tree/main/geolexica) and Typescript definitions [concept.ts](https://github.com/glossarist/paneron-extension-glossarist/blob/master/src/models/concepts.ts) and [item.ts](https://github.com/paneron/registry-kit/blob/009d72727b84c78997548d94a2095eed4eb5cc79/src/types/item.ts#L69). For Glossarist We don't need all the folders here only the 2 mentioned above and also we only need the `data` key and not the registers data for the `concepts` and `localized_concepts`.

I'm working on adding complete documentations for what is currently implemented in `Glossarist` and I'll open a PR for that once done.

**Comment by ronaldtse** [comment]
@HassanAkbar in the termium gem when I export from glossarist, in the Cli class, the generated dataset only had a flat directory with concepts as YAML files. What’s wrong with it?

**Comment by HassanAkbar** [comment]
@ronaldtse I believe the issue has been fixed in https://github.com/glossarist/glossarist-ruby/issues/84.

I will add the documentation for this in a PR for this issue -> https://github.com/glossarist/glossarist-ruby/issues/81

**Comment by HassanAkbar** [comment]
Documentation was added in this PR -> https://github.com/glossarist/glossarist-ruby/pull/90
