### ISSUE TITLE
Concept collection sorting functionality through Enumerable

### ISSUE THREAD

**Issue by ronaldtse** [glossarist/glossarist-ruby#86]
A concept collection should adopt Ruby's Enumerable interface so it can be iterated and sorted.

**Comment by HassanAkbar** [comment]
@ronaldtse This has already been done [here](https://github.com/glossarist/glossarist-ruby/blob/main/lib/glossarist/managed_concept_collection.rb#L5C5-L5C23), will add this to the documentation as well.

**Comment by HassanAkbar** [comment]
@ronaldtse the concept collection inherits from the `Enumerable` module and is also added to the documentation [here](https://github.com/glossarist/glossarist-ruby#managedconceptcollection).
Should we close this now?

**Comment by ronaldtse** [comment]
That's perfect. Thanks!
